### ISSUE TITLE
Esri Webmap Not Loading

### ISSUE THREAD

**Issue by alexatodd** [ssylvia/map-journal-index-map-demo#1]
After following the instructions exactly and checking it all ways back and forth and a colleague checking it as well, the map will not load. The frame for the map is there as is the “index-map-helper” and “index-map-info” text. This makes me think the issue has something to do with the communication between the code/our internal server and the Esri JavaScript API (esri/map).

Esri Customer Service rep. advised I post the issue here:

"I found out the application was unable to call out the JavaScript code inside the index.html...I am afraid to inform you that there is no positive progress or workaround for now, the most we can do now is register the issue on the github repository and wait for it to be resolved by the owner of that repository."

**Comment by ssylvia** [comment]
Hi Alex, I assume you are following this [blog post](https://developerscorner.storymaps.arcgis.com/add-context-to-story-map-journal-with-an-index-map-ccc3c8ca12b5) to add an index-map to your storymap-journal? That blog post was written a couple years ago and used an earlier version of our [storymap-journal](https://github.com/Esri/storymap-journal) as it's base.

Since then, Chrome deprecated the method of loading JavaScript files we we're using. This introduced a breaking change to this blog-post. Instead of adding the custom scripts to the index.html file, we had to move them to a separate file that would be loaded later in the code. I went through an updated this code base to make sure everything would still work with the latest version. I also went back and updated the blog post with new line numbers and the correct location for the JavaScript.

**Comment by alexatodd** [comment]
Thanks! That helped, but it's still not functioning properly. The basemap loads when the website first opens but not the csv points. When the sections are active the points appear and the basemap disappears. Any thoughts as to what may be the issue?

**Comment by ssylvia** [comment]
I wouldn't be able to tell without seeing your app (and code). Did you follow all the new instructions exactly? My version of the app works as expected? Did you also follow all the general map journal instructions explained in the repo's readme to setup a development version?

**Comment by alexatodd** [comment]
Yes, I followed the instructions exactly but did not set up a development version of the story map journal. After setting up the dev environment by following the instructions on GitHub, still the same issue is occurring where the map appears when the site first loads but not the csv layer; and the csv layer appears when the sections activate and the map disappears. Attached is the zipped deploy folder—I edited index.html and custom-scripts.js and added the csv file in resources (as well as some images).

**Comment by alexatodd** [comment]
I figured out the problem! It had to do with the csv file—the lat and long labels were switched. The map would disappear when the points appeared because they were out of range of the defined map. And the points looked funny because they were missing the longitude. Once I changed the csv header order from "Label,**Longitude,Latitude**,Active,StoryIndex" to "Label,**Latitude,Longitude**,Active,StoryIndex" it is working!
